export const participants = [
    {   name: "Gwyn", 
        email: "gbevans1@swarthmore.edu", 
        winner: false, 
        message: "Gwyneth Thanks for filling out my survey! 😍, come back to swat please",
    }, 
    {
        name: "Gabriel", 
        email: "gsalas1@swarthmore.edu", 
        winner: false, 
        message: "Thanks for filling out my survey Gabe :)"
    }, 
    {   name: "Rei", 
        email: "rkawaka1@swarthmore.edu", 
        winner: false, 
        message: "Hi Rei! Thanks for filling out my survey!",
    },
    {   name: "Sam", 
        email: "slian1@swarthmore.edu", 
        winner: false, 
        message: "Alright big guy, thanks I guess.",
    },
    {   name: "Nour", 
        email: "nalajar1@swarthmore.edu", 
        winner: true, 
        message: "Yay, you're the winner!! Also, thanks for filling out my survey! love love love you",
    },
    {   name: "Chris", 
        email: "cngo1@swarthmore.edu", 
        winner: false, 
        message: "Thanks pookie :P",
    },
    {   name: "Sonja", 
        email: "srebarb1@swarthmore.edu", 
        winner: false, 
        message: "Sonjyaaaa, thanks!",
    },
    {   name: "Ye", 
        email: "ylin5@swarthmore.edu", 
        winner: false, 
        message: "Tung tung tung tung sahur (I'm removing this soon)!",
    },
    {   name: "Pedro", 
        email: "pennes1@swarthmore.edu", 
        winner: false, 
        message: "Pookie Pedro, appreciate and love you king!",
    },
    {   name: "Yeyoon", 
        email: "ysong1@swarthmore.edu", 
        winner: false, 
        message: "Yoon, thanks for filling out my survey even though you probably did it wrong!",
    },
    {   name: "Ben", 
        email: "bwang2@swarthmore.edu", 
        winner: false, 
        message: "Ben, thanks for filling out my survey! Good luck this summer!!",
    },
    {   name: "Steven", 
        email: "snelson2@swarthmore.edu", 
        winner: false, 
        message: "Steven, I appreciate you even though you don't come to volleyball.",
    },
    {   name: "Tina", 
        email: "tchen7@swarthmore.edu", 
        winner: false, 
        message: "Tina (like Nina), thank you for filling out my surveyyy 🙏🏼",
    },
    {   name: "Nela", 
        email: "nloftin1@swarthmore.edu", 
        winner: false, 
        message: "Nela! Thanks so much for filling out my survey queen. ",
    },
    {   name: "Abdullah", 
        email: "aali2@swarthmore.edu", 
        winner: false, 
        message: "Pookie, appreciate you so much king!",
    },
]